### ISSUE TITLE
hi Scott / can you please commit the workspace file?

### ISSUE THREAD

**Issue by johndpope** [slcott/MusicNotation#1]
I'm bumping up against some platform targeting issues after running pod install > build. 
LayerResponder.h
//#ifdef TARGET_OS_IPHONE
//@protocol LayerResponder <NSObject>
//@end
//#elif TARGET_OS_MAC

Thanks in advance - looking for to giving this framework a test drive.

P.S. there are some included sound font files that got added to this repo that > 100mb.
I'm not sure easiest way to cull these. You may want to start again.

**Comment by slcott** [comment]
Hi John,

I rm'd the extraneous sf2 files. The repo should be significantly smaller now.

There are two targets:
1 Notation Catalog
2 Notation Catalog Mobile  

2 has some build errors, use 1 which builds for mac, not iOS, unless you wanna get the iOS version working.

Steps to test it out:
git clone git@github.com:slcott/MusicNotation.git
pod install
open workspace 
run “Notation Catalog”
choose “Accidental Test Type”. This should run that test. 

Maybe half of the notation framework is working reasonably well, but I kept changing my test framework.
Accidental Test is currently the only working test. A lot of other tests just need to be updated and use Accidental Test as a guide.
AccidentalTest.m is 1200 lines long and there are a ton of test files so it’s a bit tedious.

If you can help out that would be awesome.
Open in a browser MusicNotation/vexflow-master/tests/flow.html to see corresponding javascript vexflow tests.

If there’s a particular type of notation that you’d like to see, check out if there’s a test and if the test has a lib file fleshed out.
There’s maybe a 40% chance there is. 

There are of course still bugs.

And I added this message to the README.md for others to chip in as well.

—
Scott

**Comment by slcott** [comment]
Also, try out Layer Note Test. That’s my attempt to add some cool interactivity to a note. 

—
Scott
